version: "3.9"
services:
  diabetes-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: maio-diabetes-service:local
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MODEL_DIR=/app/model
    volumes:
      - ./model:/app/model:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 3s
      retries: 5

