version: "3.9"
services:
  diabetes-api:
    image: ghcr.io/sunilsah0/maio:v0.1
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 3s
      retries: 5

